//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterApiCallerForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anbar
    {
        public long ID { get; set; }
        public string address { get; set; }
        public string date { get; set; }
        public string tel { get; set; }
        public string mobile { get; set; }
        public string senf_id { get; set; }
        public string fname { get; set; }
        public string etehadie { get; set; }
        public string family { get; set; }
        public string raste { get; set; }
        public string national_id { get; set; }
        public string postal_code { get; set; }
        public string activity_sector { get; set; }
        public string name { get; set; }
        public string province_input { get; set; }
        public string city_input { get; set; }
        public string contractor_or_agent { get; set; }
        public string type { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string user_id { get; set; }
        public string user_first_name { get; set; }
        public string full_address { get; set; }
        public string warehouse_id { get; set; }
        public string user_last_name { get; set; }
        public string error { get; set; }
        public string api_key { get; set; }
        public Nullable<System.DateTime> last_sent { get; set; }
        public string tag { get; set; }
        public string explain { get; set; }
        public string co_national_id { get; set; }
        public string company_name { get; set; }
        public string output_result { get; set; }
        public string error_farsi { get; set; }
    }
}
