//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterApiCallerForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class countround
    {
        public long ID { get; set; }
        public Nullable<int> round { get; set; }
        public Nullable<double> time_taken { get; set; }
        public Nullable<int> counter { get; set; }
        public string message { get; set; }
        public string input_type { get; set; }
    }
}
