//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterApiCallerForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstelamTime
    {
        public long ID { get; set; }
        public Nullable<int> estelam_parallel { get; set; }
        public Nullable<double> estalam_time { get; set; }
        public Nullable<int> estelam_round { get; set; }
        public string output_result { get; set; }
    }
}
