//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterApiCallerForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Key
    {
        public long ID { get; set; }
        public string api_key { get; set; }
        public string title { get; set; }
    }
}
