//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterApiCallerForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganEstelam
    {
        public long ID { get; set; }
        public string postal_code { get; set; }
        public string province_input { get; set; }
        public string city_input { get; set; }
        public string address_input { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string address { get; set; }
        public string postal_code_server { get; set; }
        public string township { get; set; }
        public string warehouse_server { get; set; }
        public string error_farsi { get; set; }
        public string error { get; set; }
        public string last_sent { get; set; }
        public string output_result { get; set; }
    }
}
