//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterApiCallerForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableQuery
    {
        public Nullable<int> time_avg { get; set; }
        public int ID { get; set; }
    }
}
